kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  namespace: demo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"